### ISSUE TITLE
[TODO] Pending things for complete landing page development

### ISSUE THREAD

**Issue by neilor** [syntaxstartup/syntaxstartup.github.io#1]
Pending:
- [ ] Write an description for _About_ page
- [ ] Write SEO description
- [ ] Build contact form functionality using JS
